package hibernate.metier;

// Generated 12 avr. 2013 15:49:55 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Compose generated by hbm2java
 */
public class Compose implements java.io.Serializable {

	private ComposeId id;
	private Articles articlesByNoCompose;
	private Articles articlesByNoComposant;
	private BigDecimal qteComposant;

	public Compose() {
	}

	public Compose(ComposeId id, Articles articlesByNoCompose,
			Articles articlesByNoComposant) {
		this.id = id;
		this.articlesByNoCompose = articlesByNoCompose;
		this.articlesByNoComposant = articlesByNoComposant;
	}

	public Compose(ComposeId id, Articles articlesByNoCompose,
			Articles articlesByNoComposant, BigDecimal qteComposant) {
		this.id = id;
		this.articlesByNoCompose = articlesByNoCompose;
		this.articlesByNoComposant = articlesByNoComposant;
		this.qteComposant = qteComposant;
	}

	public ComposeId getId() {
		return this.id;
	}

	public void setId(ComposeId id) {
		this.id = id;
	}

	public Articles getArticlesByNoCompose() {
		return this.articlesByNoCompose;
	}

	public void setArticlesByNoCompose(Articles articlesByNoCompose) {
		this.articlesByNoCompose = articlesByNoCompose;
	}

	public Articles getArticlesByNoComposant() {
		return this.articlesByNoComposant;
	}

	public void setArticlesByNoComposant(Articles articlesByNoComposant) {
		this.articlesByNoComposant = articlesByNoComposant;
	}

	public BigDecimal getQteComposant() {
		return this.qteComposant;
	}

	public void setQteComposant(BigDecimal qteComposant) {
		this.qteComposant = qteComposant;
	}

}
