package hibernate.metier;

// Generated 12 avr. 2013 15:49:55 by Hibernate Tools 4.0.0

/**
 * DetailCdeId generated by hbm2java
 */
public class DetailCdeId implements java.io.Serializable {

	private String noCommand;
	private String noArticle;

	public DetailCdeId() {
	}

	public DetailCdeId(String noCommand, String noArticle) {
		this.noCommand = noCommand;
		this.noArticle = noArticle;
	}

	public String getNoCommand() {
		return this.noCommand;
	}

	public void setNoCommand(String noCommand) {
		this.noCommand = noCommand;
	}

	public String getNoArticle() {
		return this.noArticle;
	}

	public void setNoArticle(String noArticle) {
		this.noArticle = noArticle;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailCdeId))
			return false;
		DetailCdeId castOther = (DetailCdeId) other;

		return ((this.getNoCommand() == castOther.getNoCommand()) || (this
				.getNoCommand() != null && castOther.getNoCommand() != null && this
				.getNoCommand().equals(castOther.getNoCommand())))
				&& ((this.getNoArticle() == castOther.getNoArticle()) || (this
						.getNoArticle() != null
						&& castOther.getNoArticle() != null && this
						.getNoArticle().equals(castOther.getNoArticle())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNoCommand() == null ? 0 : this.getNoCommand().hashCode());
		result = 37 * result
				+ (getNoArticle() == null ? 0 : this.getNoArticle().hashCode());
		return result;
	}

}
