package hibernate.metier;

// Generated 12 avr. 2013 15:49:55 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * DetailCde generated by hbm2java
 */
public class DetailCde implements java.io.Serializable {

	private DetailCdeId id;
	private Commandes commandes;
	private Articles articles;
	private BigDecimal qteCdee;
	private Character livree;

	public DetailCde() {
	}

	public DetailCde(DetailCdeId id, Commandes commandes, Articles articles) {
		this.id = id;
		this.commandes = commandes;
		this.articles = articles;
	}

	public DetailCde(DetailCdeId id, Commandes commandes, Articles articles,
			BigDecimal qteCdee, Character livree) {
		this.id = id;
		this.commandes = commandes;
		this.articles = articles;
		this.qteCdee = qteCdee;
		this.livree = livree;
	}

	public DetailCdeId getId() {
		return this.id;
	}

	public void setId(DetailCdeId id) {
		this.id = id;
	}

	public Commandes getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Commandes commandes) {
		this.commandes = commandes;
	}

	public Articles getArticles() {
		return this.articles;
	}

	public void setArticles(Articles articles) {
		this.articles = articles;
	}

	public BigDecimal getQteCdee() {
		return this.qteCdee;
	}

	public void setQteCdee(BigDecimal qteCdee) {
		this.qteCdee = qteCdee;
	}

	public Character getLivree() {
		return this.livree;
	}

	public void setLivree(Character livree) {
		this.livree = livree;
	}

}
